/********************************************************************************
** Form generated from reading UI file 'Frameworkhelp.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef SAMPLE_H
#define SAMPLE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_OpcodeGenerator
{
public:
    QWidget *centralwidget;
    QSlider *Param_1_val;
    QComboBox *set_get_menu;
    QLabel *do_set_get_label;
    QComboBox *tx_rx_menu;
    QSlider *Param_2_val;
    QLabel *param2_up_label;
    QLabel *param2_up_label_2;
    QLabel *tx_rx_label;
    QLabel *param1_label;
    QLabel *param2_label;
    QPushButton *SendData;
    QLabel *logo;
    QLabel *Param1_slider_val;
    QLabel *Param2_slider_val;
    QLabel *max_p1_val;
    QLabel *min_p1_val;
    QLabel *max_p2_val;
    QLabel *min_p2_val;
    QComboBox *API_menu;
    QLabel *API_label;
    QLabel *myname;
    QPlainTextEdit *Param1_input_text;
    QPlainTextEdit *Param2_input_text;
    QLabel *Insert_Opcode_label;
    QPlainTextEdit *Opcode_input_text;
    QLabel *Get_result_label;
    QLabel *Show_get_result;
    QLabel *step1;
    QLabel *step2;
    QLabel *step3;
    QLabel *step4;
    QLabel *step5;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *OpcodeGenerator)
    {
        if (OpcodeGenerator->objectName().isEmpty())
            OpcodeGenerator->setObjectName(QStringLiteral("OpcodeGenerator"));
        OpcodeGenerator->resize(738, 540);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(61, 60, 60, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(136, 138, 133, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(76, 75, 75, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(30, 30, 30, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(40, 40, 40, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        QBrush brush7(QColor(85, 87, 83, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush9(QColor(255, 255, 255, 128));
        brush9.setStyle(Qt::NoBrush);
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush10(QColor(255, 255, 255, 128));
        brush10.setStyle(Qt::NoBrush);
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush10);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush11(QColor(255, 255, 255, 128));
        brush11.setStyle(Qt::NoBrush);
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush11);
        OpcodeGenerator->setPalette(palette);
        centralwidget = new QWidget(OpcodeGenerator);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        Param_1_val = new QSlider(centralwidget);
        Param_1_val->setObjectName(QStringLiteral("Param_1_val"));
        Param_1_val->setGeometry(QRect(150, 270, 160, 24));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush12(QColor(0, 249, 255, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush12);
        QBrush brush13(QColor(127, 252, 255, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush13);
        QBrush brush14(QColor(63, 250, 255, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        QBrush brush15(QColor(0, 124, 127, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush15);
        QBrush brush16(QColor(0, 166, 170, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush17(QColor(0, 0, 0, 128));
        brush17.setStyle(Qt::NoBrush);
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush17);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush18(QColor(0, 0, 0, 128));
        brush18.setStyle(Qt::NoBrush);
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush19(QColor(0, 0, 0, 128));
        brush19.setStyle(Qt::NoBrush);
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush19);
        Param_1_val->setPalette(palette1);
        Param_1_val->setValue(50);
        Param_1_val->setSliderPosition(50);
        Param_1_val->setOrientation(Qt::Horizontal);
        set_get_menu = new QComboBox(centralwidget);
        set_get_menu->setObjectName(QStringLiteral("set_get_menu"));
        set_get_menu->setGeometry(QRect(590, 130, 110, 38));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush20(QColor(114, 159, 207, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush20);
        QBrush brush21(QColor(196, 225, 255, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush21);
        QBrush brush22(QColor(155, 192, 231, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush22);
        QBrush brush23(QColor(57, 79, 103, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush23);
        QBrush brush24(QColor(76, 106, 138, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush25(QColor(184, 207, 231, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush26(QColor(0, 0, 0, 128));
        brush26.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush26);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush21);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush22);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush23);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush25);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush27(QColor(0, 0, 0, 128));
        brush27.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush27);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush22);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush28(QColor(0, 0, 0, 128));
        brush28.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush28);
        set_get_menu->setPalette(palette2);
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        set_get_menu->setFont(font);
        do_set_get_label = new QLabel(centralwidget);
        do_set_get_label->setObjectName(QStringLiteral("do_set_get_label"));
        do_set_get_label->setGeometry(QRect(600, 100, 91, 22));
        QFont font1;
        font1.setFamily(QStringLiteral("Utopia"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        do_set_get_label->setFont(font1);
        tx_rx_menu = new QComboBox(centralwidget);
        tx_rx_menu->setObjectName(QStringLiteral("tx_rx_menu"));
        tx_rx_menu->setGeometry(QRect(460, 130, 110, 38));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush20);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush21);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush22);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush23);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush24);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush29(QColor(0, 0, 0, 128));
        brush29.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Active, QPalette::PlaceholderText, brush29);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush20);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush22);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush23);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush24);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush20);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush25);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush30(QColor(0, 0, 0, 128));
        brush30.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush21);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush22);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush31(QColor(0, 0, 0, 128));
        brush31.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush31);
        tx_rx_menu->setPalette(palette3);
        tx_rx_menu->setFont(font);
        Param_2_val = new QSlider(centralwidget);
        Param_2_val->setObjectName(QStringLiteral("Param_2_val"));
        Param_2_val->setGeometry(QRect(150, 340, 160, 24));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush12);
        QBrush brush32(QColor(126, 253, 255, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush32);
        QBrush brush33(QColor(63, 251, 255, 255));
        brush33.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush33);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush12);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush34(QColor(0, 0, 0, 128));
        brush34.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush34);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush32);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush33);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush35(QColor(0, 0, 0, 128));
        brush35.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush32);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush33);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush36(QColor(0, 0, 0, 128));
        brush36.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush36);
        Param_2_val->setPalette(palette4);
        Param_2_val->setValue(50);
        Param_2_val->setOrientation(Qt::Horizontal);
        param2_up_label = new QLabel(centralwidget);
        param2_up_label->setObjectName(QStringLiteral("param2_up_label"));
        param2_up_label->setGeometry(QRect(200, 230, 68, 22));
        param2_up_label->setFont(font1);
        param2_up_label_2 = new QLabel(centralwidget);
        param2_up_label_2->setObjectName(QStringLiteral("param2_up_label_2"));
        param2_up_label_2->setGeometry(QRect(200, 310, 68, 22));
        QFont font2;
        font2.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        param2_up_label_2->setFont(font2);
        tx_rx_label = new QLabel(centralwidget);
        tx_rx_label->setObjectName(QStringLiteral("tx_rx_label"));
        tx_rx_label->setGeometry(QRect(480, 100, 91, 22));
        tx_rx_label->setFont(font1);
        param1_label = new QLabel(centralwidget);
        param1_label->setObjectName(QStringLiteral("param1_label"));
        param1_label->setGeometry(QRect(140, 140, 81, 22));
        param1_label->setFont(font1);
        param2_label = new QLabel(centralwidget);
        param2_label->setObjectName(QStringLiteral("param2_label"));
        param2_label->setGeometry(QRect(30, 140, 91, 22));
        param2_label->setFont(font1);
        SendData = new QPushButton(centralwidget);
        SendData->setObjectName(QStringLiteral("SendData"));
        SendData->setGeometry(QRect(540, 320, 99, 38));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(SendData->sizePolicy().hasHeightForWidth());
        SendData->setSizePolicy(sizePolicy);
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush37(QColor(115, 210, 22, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush37);
        QBrush brush38(QColor(170, 255, 87, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush38);
        QBrush brush39(QColor(142, 232, 54, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush39);
        QBrush brush40(QColor(57, 105, 11, 255));
        brush40.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush40);
        QBrush brush41(QColor(76, 140, 14, 255));
        brush41.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush41);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush37);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush42(QColor(185, 232, 138, 255));
        brush42.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush42);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush43(QColor(0, 0, 0, 128));
        brush43.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush43);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush37);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush38);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush39);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush40);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush41);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush37);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush42);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush44(QColor(0, 0, 0, 128));
        brush44.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush37);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush39);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush41);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush37);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush37);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush37);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush45(QColor(0, 0, 0, 128));
        brush45.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush45);
        SendData->setPalette(palette5);
        QFont font3;
        font3.setFamily(QStringLiteral("Utopia"));
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setItalic(true);
        font3.setWeight(75);
        SendData->setFont(font3);
        logo = new QLabel(centralwidget);
        logo->setObjectName(QStringLiteral("logo"));
        logo->setGeometry(QRect(270, 0, 171, 91));
        logo->setContextMenuPolicy(Qt::NoContextMenu);
        logo->setPixmap(QPixmap(QString::fromUtf8(":/icon/external-content.duckduckgo.com.png")));
        logo->setScaledContents(true);
        Param1_slider_val = new QLabel(centralwidget);
        Param1_slider_val->setObjectName(QStringLiteral("Param1_slider_val"));
        Param1_slider_val->setGeometry(QRect(220, 290, 68, 22));
        QFont font4;
        font4.setPointSize(11);
        font4.setBold(true);
        font4.setWeight(75);
        Param1_slider_val->setFont(font4);
        Param2_slider_val = new QLabel(centralwidget);
        Param2_slider_val->setObjectName(QStringLiteral("Param2_slider_val"));
        Param2_slider_val->setGeometry(QRect(210, 360, 68, 22));
        Param2_slider_val->setFont(font4);
        max_p1_val = new QLabel(centralwidget);
        max_p1_val->setObjectName(QStringLiteral("max_p1_val"));
        max_p1_val->setGeometry(QRect(330, 270, 68, 22));
        max_p1_val->setFont(font1);
        min_p1_val = new QLabel(centralwidget);
        min_p1_val->setObjectName(QStringLiteral("min_p1_val"));
        min_p1_val->setGeometry(QRect(60, 270, 68, 22));
        min_p1_val->setFont(font1);
        max_p2_val = new QLabel(centralwidget);
        max_p2_val->setObjectName(QStringLiteral("max_p2_val"));
        max_p2_val->setGeometry(QRect(330, 340, 68, 22));
        max_p2_val->setFont(font1);
        min_p2_val = new QLabel(centralwidget);
        min_p2_val->setObjectName(QStringLiteral("min_p2_val"));
        min_p2_val->setGeometry(QRect(60, 340, 68, 22));
        min_p2_val->setFont(font1);
        API_menu = new QComboBox(centralwidget);
        API_menu->setObjectName(QStringLiteral("API_menu"));
        API_menu->setGeometry(QRect(230, 130, 201, 38));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush20);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush21);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush22);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush23);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush24);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush46(QColor(0, 0, 0, 128));
        brush46.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Active, QPalette::PlaceholderText, brush46);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush20);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush21);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush22);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush23);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush24);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush20);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush25);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        QBrush brush47(QColor(0, 0, 0, 128));
        brush47.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush23);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush20);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush21);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush22);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush23);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush24);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush23);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush23);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush20);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush20);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush20);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        QBrush brush48(QColor(0, 0, 0, 128));
        brush48.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush48);
        API_menu->setPalette(palette6);
        API_menu->setFont(font);
        API_label = new QLabel(centralwidget);
        API_label->setObjectName(QStringLiteral("API_label"));
        API_label->setGeometry(QRect(320, 100, 68, 22));
        API_label->setFont(font1);
        myname = new QLabel(centralwidget);
        myname->setObjectName(QStringLiteral("myname"));
        myname->setGeometry(QRect(540, 420, 131, 22));
        QFont font5;
        font5.setFamily(QStringLiteral("Utopia"));
        font5.setItalic(true);
        myname->setFont(font5);
        Param1_input_text = new QPlainTextEdit(centralwidget);
        Param1_input_text->setObjectName(QStringLiteral("Param1_input_text"));
        Param1_input_text->setGeometry(QRect(400, 270, 104, 31));
        Param2_input_text = new QPlainTextEdit(centralwidget);
        Param2_input_text->setObjectName(QStringLiteral("Param2_input_text"));
        Param2_input_text->setGeometry(QRect(400, 330, 104, 31));
        Insert_Opcode_label = new QLabel(centralwidget);
        Insert_Opcode_label->setObjectName(QStringLiteral("Insert_Opcode_label"));
        Insert_Opcode_label->setGeometry(QRect(530, 240, 151, 22));
        Insert_Opcode_label->setFont(font1);
        Opcode_input_text = new QPlainTextEdit(centralwidget);
        Opcode_input_text->setObjectName(QStringLiteral("Opcode_input_text"));
        Opcode_input_text->setGeometry(QRect(540, 270, 104, 31));
        Get_result_label = new QLabel(centralwidget);
        Get_result_label->setObjectName(QStringLiteral("Get_result_label"));
        Get_result_label->setGeometry(QRect(300, 390, 101, 22));
        QFont font6;
        font6.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font6.setPointSize(12);
        font6.setBold(true);
        font6.setWeight(75);
        Get_result_label->setFont(font6);
        Show_get_result = new QLabel(centralwidget);
        Show_get_result->setObjectName(QStringLiteral("Show_get_result"));
        Show_get_result->setGeometry(QRect(230, 410, 241, 51));
        Show_get_result->setFont(font2);
        Show_get_result->setAlignment(Qt::AlignCenter);
        step1 = new QLabel(centralwidget);
        step1->setObjectName(QStringLiteral("step1"));
        step1->setGeometry(QRect(620, 170, 61, 21));
        step1->setFont(font4);
        step2 = new QLabel(centralwidget);
        step2->setObjectName(QStringLiteral("step2"));
        step2->setGeometry(QRect(490, 170, 47, 21));
        step2->setFont(font4);
        step3 = new QLabel(centralwidget);
        step3->setObjectName(QStringLiteral("step3"));
        step3->setGeometry(QRect(310, 170, 51, 21));
        step3->setFont(font4);
        step4 = new QLabel(centralwidget);
        step4->setObjectName(QStringLiteral("step4"));
        step4->setGeometry(QRect(100, 210, 47, 20));
        step4->setFont(font4);
        step5 = new QLabel(centralwidget);
        step5->setObjectName(QStringLiteral("step5"));
        step5->setGeometry(QRect(650, 330, 51, 21));
        step5->setFont(font4);
        OpcodeGenerator->setCentralWidget(centralwidget);
        menubar = new QMenuBar(OpcodeGenerator);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 738, 21));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        OpcodeGenerator->setMenuBar(menubar);
        statusbar = new QStatusBar(OpcodeGenerator);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        OpcodeGenerator->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());

        retranslateUi(OpcodeGenerator);
        QObject::connect(Param_2_val, SIGNAL(valueChanged(int)), Param2_slider_val, SLOT(setNum(int)));
        QObject::connect(Param_1_val, SIGNAL(valueChanged(int)), Param1_slider_val, SLOT(setNum(int)));

        QMetaObject::connectSlotsByName(OpcodeGenerator);
    } // setupUi

    void retranslateUi(QMainWindow *OpcodeGenerator)
    {
        OpcodeGenerator->setWindowTitle(QApplication::translate("OpcodeGenerator", "MainWindow", Q_NULLPTR));
        set_get_menu->clear();
        set_get_menu->insertItems(0, QStringList()
         << QApplication::translate("OpcodeGenerator", "None", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "set", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "get", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "do", Q_NULLPTR)
        );
        do_set_get_label->setText(QApplication::translate("OpcodeGenerator", "Set,Get,Do", Q_NULLPTR));
        tx_rx_menu->clear();
        tx_rx_menu->insertItems(0, QStringList()
         << QApplication::translate("OpcodeGenerator", "None", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "RX", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "TX", Q_NULLPTR)
         << QApplication::translate("OpcodeGenerator", "TRX", Q_NULLPTR)
        );
        param2_up_label->setText(QApplication::translate("OpcodeGenerator", "Param1", Q_NULLPTR));
        param2_up_label_2->setText(QApplication::translate("OpcodeGenerator", "Param2", Q_NULLPTR));
        tx_rx_label->setText(QApplication::translate("OpcodeGenerator", "Rx,Tx,Trx", Q_NULLPTR));
        param1_label->setText(QApplication::translate("OpcodeGenerator", "Param1", Q_NULLPTR));
        param2_label->setText(QApplication::translate("OpcodeGenerator", "Param2", Q_NULLPTR));
        SendData->setText(QApplication::translate("OpcodeGenerator", "Send", Q_NULLPTR));
        logo->setText(QString());
        Param1_slider_val->setText(QString());
        Param2_slider_val->setText(QString());
        max_p1_val->setText(QApplication::translate("OpcodeGenerator", "MaxP1", Q_NULLPTR));
        min_p1_val->setText(QApplication::translate("OpcodeGenerator", "MinP1", Q_NULLPTR));
        max_p2_val->setText(QApplication::translate("OpcodeGenerator", "MaxP2", Q_NULLPTR));
        min_p2_val->setText(QApplication::translate("OpcodeGenerator", "MinP2", Q_NULLPTR));
        API_menu->clear();
        API_menu->insertItems(0, QStringList()
         << QApplication::translate("OpcodeGenerator", "None", Q_NULLPTR)
        );
        API_label->setText(QApplication::translate("OpcodeGenerator", "API", Q_NULLPTR));
        myname->setText(QApplication::translate("OpcodeGenerator", "Designed by Tonix", Q_NULLPTR));
        Param1_input_text->setPlaceholderText(QApplication::translate("OpcodeGenerator", "50", Q_NULLPTR));
        Param2_input_text->setPlaceholderText(QApplication::translate("OpcodeGenerator", "50", Q_NULLPTR));
        Insert_Opcode_label->setText(QApplication::translate("OpcodeGenerator", "Insert/Get OpCode", Q_NULLPTR));
        Opcode_input_text->setPlaceholderText(QApplication::translate("OpcodeGenerator", "0x0000", Q_NULLPTR));
        Get_result_label->setText(QApplication::translate("OpcodeGenerator", "GET RESULT", Q_NULLPTR));
        Show_get_result->setText(QApplication::translate("OpcodeGenerator", "None", Q_NULLPTR));
        step1->setText(QApplication::translate("OpcodeGenerator", "Step 1", Q_NULLPTR));
        step2->setText(QApplication::translate("OpcodeGenerator", "Step 2", Q_NULLPTR));
        step3->setText(QApplication::translate("OpcodeGenerator", "Step 3", Q_NULLPTR));
        step4->setText(QApplication::translate("OpcodeGenerator", "Step 4", Q_NULLPTR));
        step5->setText(QApplication::translate("OpcodeGenerator", "Step 5", Q_NULLPTR));
        menuFile->setTitle(QApplication::translate("OpcodeGenerator", "File", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class OpcodeGenerator: public Ui_OpcodeGenerator {};
} // namespace Ui

QT_END_NAMESPACE

#endif // SAMPLE_H
